from argparse import ArgumentParser
from collections import defaultdict
from textwrap import dedent

from formatter import Formatter


class _BGPFormatter(Formatter):
    "Basic Formatter for BGP configurations"

    def populate_argument_parser(self, parser):
        parser.add_argument("-4",
                            dest="family",
                            action="store_const",
                            const="ipv4",
                            help="Generate IPv4 config")
        parser.add_argument("-6",
                            dest="family",
                            action="store_const",
                            const="ipv6",
                            help="Generate IPv6 config")
        parser.add_argument("-p", "--prefix", dest="prefix",
                            help="Prefix for protocol names, e.g. bgp_icvpn_<community>",
                            metavar="PREFIX",
                            default="")
        parser.add_argument("-d", "--default",
                            dest="defaulttemplate",
                            help="Default template/peer-group to use",
                            metavar="TEMPLATE",
                            default=None)
        parser.add_argument("-t", "--template",
                            dest="templates",
                            action="append",
                            help="Define protocol template/peer-group" +
                                 "for community",
                            metavar="COMMUNITY:TEMPLATE",
                            default=[])
        parser.set_defaults(family="ipv6")

    def generate_config(self, arguments, communities):

        template = defaultdict(lambda: arguments.defaulttemplate)
        template.update(dict(map(lambda s: s.split(":"), arguments.templates)))

        family = arguments.family

        for community, data in communities:
            try:
                bgp = data["bgp"]
                asn = data["asn"]
            except (TypeError, KeyError):
                continue

            for host in sorted(bgp.keys()):
                d = bgp[host]
                if family not in d:
                    continue

                peer = d[family]
                self.config.append(
                    dedent(self.config_template %
                           {"prefix": arguments.prefix + host,
                            "template": template[community],
                            "peer": peer,
                            "asn": asn}))


class BirdFormatter(_BGPFormatter):
    "Formatter for bind9 using type forward"

    config_template = """
            protocol bgp %(prefix)s from %(template)s {
                neighbor %(peer)s as %(asn)s;
            }
        """


class QuaggaFormatter(_BGPFormatter):
    "Formatter for quagga"

    config_template = """
            neighbor %(peer)s remote-as %(asn)s
            neighbor %(peer)s description %(prefix)s
            neighbor %(peer)s peer-group %(template)s
        """


class BirdRoaFormatter(_BGPFormatter):
    "Formatter for roa table in bird format"

    def populate_argument_parser(self, parser):
        super(BirdRoaFormatter, self).populate_argument_parser(parser)
        parser.add_argument("-m", "--max",
                            dest="default_max_prefixlen",
                            default=0,
                            type=int,
                            help="max prefix length to accept")

    def generate_config(self, arguments, communities):

        family = arguments.family
        default_max_prefixlen = arguments.default_max_prefixlen

        self.config.append(dedent(
            """
            # This file is automatically generated.
            # You need to add the surrounding roa table statement yourself.
            # So Include it via:
            #   roa table icvpn { include "roa.con?" }
            """
            ))

        network_data = []

        for community, data in communities:
            try:
                networks = data["networks"][family]
                asn = data["asn"]
            except (TypeError, KeyError):
                continue

            for network in sorted(networks):
                prefixlen = int(network.split("/")[1])
                if prefixlen > default_max_prefixlen:
                    max_prefixlen = prefixlen
                else:
                    max_prefixlen = default_max_prefixlen
                network_data.append((network, max_prefixlen, asn, community))

        maxlen_net = str(max(map(lambda x: len(x[0]), network_data)))
        maxlen_as = str(max(map(lambda x: len(str(x[2])), network_data)))

        for entry in network_data:
            self.config.append("roa {subnet:<{len_net}} max {max_prefix_len:>3} as {asn:>{len_asn}}; # {community}".format(
                subnet=entry[0], max_prefix_len=entry[1], asn=entry[2], community=entry[3],
                len_net=maxlen_net, len_asn=maxlen_asn
            ))
