#!/usr/bin/env python

import os
import sys
import yaml
import ipaddress
from optparse import OptionParser

def error(*arg):
    print(*arg, file=sys.stderr)

def ip_family_address(family, address):
    return getattr(ipaddress, family[:2].upper() + family[2:] + "Address")(address)

def ip_family_network(family, network):
    return getattr(ipaddress, family[:2].upper() + family[2:] + "Network")(network)

def check_dupe(name, v, d, community):
    errcnt = 0

    if v in d:
        errcnt += 1
        error("Duplicate %s (%s):" % (name, v), d[v], community)

    if errcnt == 0:
        d[v] = community

    return errcnt

def check_net(family, net, nets, community):
    errcnt = 0

    try:
        net = ip_family_network(family, net)
    except ValueError:
        errcnt += 1
        error("Not an %s network: %s (%s)" % (family, net, community))
    else:
        for other in nets:
            if other.overlaps(net):
                errcnt += 1
                error("%s Network overlap: %s (%s), %s (%s)" % (family, community, net, nets[other], other))

        if errcnt == 0:
            nets[net] = community

    return errcnt

def do_checks(srcdir):
    """
    Check files for sanity.
    """

    asns = dict()
    bgp_gw = dict()
    bgp_gw_ip = dict()
    networks = {'IPv4': dict(), 'IPv6': dict()}
    errcnt = 0

    for fname in sorted(list(set(os.listdir(srcdir)))):
        if fname.startswith("."):
            continue

        if fname.startswith("README"):
            continue

        fpath = os.path.join(srcdir, fname)
        if os.path.isfile(fpath):
            with open(fpath) as f:
                data = yaml.load(f)
                community = fname
                print("Checking", community)

                if 'asn' in data:
                    errcnt += check_dupe("ASN", data['asn'], asns, community)

                if 'bgp' in data:
                    for bgp in data['bgp']:
                        errcnt += check_dupe("BGP peer name", bgp, bgp_gw, community)

                        for ipclass in data['bgp'][bgp]:
                            try:
                                ip = ip_family_address(ipclass, data['bgp'][bgp][ipclass])
                                errcnt += check_dupe("BGP IP", ip, bgp_gw_ip, community)
                            except ValueError:
                                errcnt += 1
                                error("Not an %s BGP address: %s (%s)" % (ipclass, data['bgp'][bgp][ipclass], community))

                if 'networks' in data:
                    for family in ('IPv4', 'IPv6'):
                        if family.lower() in data['networks']:
                            for net in data['networks'][family.lower()]:
                                errcnt += check_net(family, net, networks[family], community)

    print("%d error(s)" % errcnt)

    return 0 if errcnt == 0 else 1

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-s", "--sourcedir", dest="src",
        help="Use files in DIR as input files. Default: data/", metavar="DIR",
        default="data")

    (options, args) = parser.parse_args()

    ret = do_checks(options.src)
    
    sys.exit(ret)
